import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import Navigation from "@/app/common/Navigation";
import { AuthProvider } from "@/app/utils/AuthContect";
import LoginModal from "@/app/common/LoginModal";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// import StoreProvider from "@/app/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bilinguist Kid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <StoreProvider> */}
          <AppRouterCacheProvider>
            <CssBaseline />
            <Navigation />
              {children}
          </AppRouterCacheProvider>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
